---
name: Build/Push to Docker
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 0'
  push:
    branches:
      - 'master'
jobs:
  docker:
    strategy:
      matrix:
        version: [ 2.11, 2.14 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.version }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: phlcrny/ansible:${{ matrix.version }}
...
