---
name: Push to Docker
on:
  push:
    branches: [ master ]
    paths:
    - 'Dockerfile'
    - '.github/workflows/**'
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '30 10 * * 0'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push test
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: phlcrny/ansible:${{ GITHUB_SHA }}

      - name: Test ansible
        run: |
          docker run --rm phlcrny/ansible:${{ GITHUB_SHA }} ansible --version

      - name: Test ansible-playbook
        run: |
          docker run --rm phlcrny/ansible:${{ GITHUB_SHA }} ansible-playbook --version

      - name: Test ansible-galaxy
        run: |
          docker run --rm phlcrny/ansible:${{ GITHUB_SHA }} ansible-galaxy --version

      - name: Test ansible-lint
        run: |
          docker run --rm phlcrny/ansible:${{ GITHUB_SHA }} ansible-lint --version

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: phlcrny/ansible:latest
...